FROM node as build

WORKDIR  /falconEmail
COPY  ../falconEmailFrontend/package*.json ./
RUN npm install

COPY  ../falconEmailFrontend ./

RUN npm run build

EXPOSE 8080
CMD [ "npm", "run", "server" ]
 

# FROM nginx:stable-alpine as production-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
